### ISSUE TITLE
Crashing During Startup (1.17)

### ISSUE THREAD

**Issue by jakey1995abc** [juliand665/Dynamic-FPS#25] opened 2021-06-18 19:55 UTC
Crash log:

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 6/18/21, 8:51 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dynamicfps'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1225)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:99)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:157)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at dynamicfps.DynamicFPSConfig.load(DynamicFPSConfig.java:31)
	at dynamicfps.DynamicFPSMod.onInitialize(DynamicFPSMod.java:41)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 284622280 bytes (271 MiB) / 589299712 bytes (562 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f08
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6663
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32693.82
	Virtual memory used (MB): 21357.11
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 952.39
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		ambientenvironment: Ambient Environment fabric-1.17-rc2-6.0.0.11
		amecsapi: Amecs API 1.1.4+mc21w16a
		antighost: AntiGhost 1.17-fabric0.34.9-1.1.4
		architectury: Architectury 2.0.9
		attributefix: Attribute Fix {FABRIC} 1.0.1
		authme: Auth Me 1.5.0
		beenfo: Beenfo 1.17-fabric0.34.9-1.3.1
		betterbeds: Better Beds 1.2.0
		bettercontrols: Better Controls 1.2.0
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterthirdperson: Better Third Person 1.5.0
		big_items_duh: Big items, duh! 1.0.2+mc1.17-rc2
		blue_endless_jankson: jankson 1.2.1
		boostedbrightness: Boosted Brightness 2.0.0
		chat-up: Chat Up! 2.0
		cherishedworlds: Cherished Worlds 1.4.1-1.17
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cleancut: CleanCut 1.17-4.0-fabric
		clear-skies: Clear Skies 1.5.68
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps fabric-1.17-7.0.0.2
		colormeoutlines: Color Me Outlines 1.0.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		completeconfig: CompleteConfig 1.0.0
		controlling: Controlling For Fabric 1.1.2
		craftpresence: CraftPresence 1.8.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		dark-loading-screen: Dark Loading Screen 1.6.5
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		durabilityviewer: Giselbaers Durability Viewer 1.17-fabric0.34.9-1.10.1
		dynamicfps: Dynamic FPS 2.0.4
		dynmus: Dynamic Music 1.3.0
		editsign: EditSign 2.2.1
		enchantedtooltips: Enchanted ToolTips 1.3.5-1.17
		enchantmentdescriptions: Enchantment Descriptions 3.0.11
		entityculling: EntityCulling-Fabric 1.2.3
		fabric: Fabric API 0.35.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+1d383bb63d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b44633d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		fabrilousupdater: FabrilousUpdater 2.2
		fallingleaves: Falling Leaves 1.7.0+1.17
		fallingtree: FallingTree 2.11.5
		fancymenu: FancyMenu 2.1.1
		fastchest: FastChest 1.2+1.17
		fastfurnace: FastFurnace 1.17-3.0
		gamesensemod: GameSense Mod 1.0.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		itemmodelfix: Item Model Fix 1.0.2+1.17
		itemscroller: Item Scroller 0.15.0-dev.20210608.211652
		java: OpenJDK 64-Bit Server VM 16
		jukefix: JukeFix 1.0.1
		keepheadnames: Keep Head Names 1.3
		kirin: Kirin UI 1.8.7-1.17
		konkrete: Konkrete 1.2.0
		krypton: Krypton 0.1.3
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		lightoverlay: Light Overlay 6.0.0
		lithium: Lithium 0.7.1
		lock_minecart_view: Better minecart rotation 1.2.1
		logical_zoom: Logical Zoom 0.0.9
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17
		minecraftcapes: MinecraftCapes Mod 10
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.2
		multiconnect: MultiConnect 1.4.4
		multiconnect-api: MultiConnect API 1.4.4
		nameless_servers: Nameless Servers 1.0.0+1.17
		nofade: No Fade 1.17-2.0.0
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_yaml_snakeyaml: snakeyaml 1.29
		petowner: Pet Owner 1.8.1-1.17-rc1+
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		rad: Reload Audio Driver 1.0.1
		resolutioncontrol: ResolutionControl+ 3.0.0
		roughlyenoughitems: Roughly Enough Items 6.0.251-alpha
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0-alpha.4+1.17
		silkspawners: SilkSpawners 1.0.2
		spark: spark ${pluginVersion}
		spruceui: SpruceUI 3.2.0+1.17
		tooltipfix: ToolTip Fix 1.0.3-1.16
		uglyscoreboardfix: Ugly Scoreboard Fix 2.3.1
		viabackwards: ViaBackwards 4.0.0
		viafabric: ViaFabric 0.4.1+189-main
		viafabric-mc117: ViaFabric for 1.17 0.4.1+189-main
		viaversion: ViaVersion 4.0.1-SNAPSHOT
		wthit: wthit 3.5.3
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by juliand665** [comment] 2021-06-18 19:57
Huh, very strange. Does it work with [version 2.0.3](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps/files/3343747)?

**Comment by Samisaprogrammer** [comment] 2021-06-29 07:12
hey, unrelated but please update modrinth

**Comment by juliand665** [comment] 2021-06-29 12:57
@Samisaprogrammer Thanks for the reminder! A new issue would have been more appropriate, but still. The update is up now :)

**Comment by Samisaprogrammer** [comment] 2021-06-30 07:33
thanks!

**Comment by altrisi** [comment] 2021-08-12 19:54
This seems like it's caused by fabricmc/fabric-loader#225.

Therefore it should be a rare crash, and can't be fixed from the mod side.

I'll bump that issue on fabricord lets see what happens.

**Comment by juliand665** [comment] 2021-10-16 23:20
Should be fixed, since the cause of the issue was apparently addressed back on August 13, likely thanks to @altrisi's bump :heart:

**Closed by juliand665** 2021-10-16 23:20 UTC
