### ISSUE TITLE
[Bug] Frames aren't getting rendered properly when on idle

### ISSUE THREAD

**Issue by Blobanium** [juliand665/Dynamic-FPS#47] opened 2021-12-10 23:31 UTC
So, i have come across a bug in 1.18 where it seems to be black but for a split second it shows a frame and then it goes black again... it does this every time i tab out.

Replay footage of this happening: https://streamable.com/f0xzhd

**Comment by JinxTheGoblin** [comment] 2021-12-12 16:46
I've been getting this same thing happening to me too

**Comment by JinxTheGoblin** [comment] 2021-12-12 17:02
might be caused by figura, but not sure

**Comment by juliand665** [comment] 2021-12-13 03:28
Very strange! Does it still happen with just Dynamic FPS (and Fabric API)?

**Comment by JinxTheGoblin** [comment] 2021-12-13 21:22
nope, just when figura is installed alongside

**Comment by juliand665** [comment] 2021-12-19 17:27
fixed in figura :)

**Closed by juliand665** 2021-12-19 17:27 UTC
