### ISSUE TITLE
Screen flicker when game is in the background during a Discord screenshare

### ISSUE THREAD

**Issue by prototype464** [juliand665/Dynamic-FPS#49] opened 2022-02-03 17:35 UTC
I noticed a really bad issue (for anyone with epileptic disorders) when using this mod - When screensharing the game window (whether sharing the game window itself or even the entire screen), the game will flicker in the Discord preview, rapidly flashing between a black screen and the game.

Steps to reproduce are just to use this mod, set the FPS to 10 or 15 (anywhere around there), open up a Discord screenshare, have Discord focused, and see the preview.

**Comment by juliand665** [comment] 2022-02-04 04:11
That's really strange! I can't reproduce this on my setup (macOS 12.2, AMD Radeon Pro 5500M).
- What is your platform and GPU?
- I assume you're using the newest version of the mod on 1.18.1—is that correct?
- Does it still happen with just Dynamic FPS (and Fabric API) and nothing else?
- Does it still happen with other target FPS values than the 10-15 range you listed? e.g. 1 FPS

I could try it on Windows too when I next boot into it.

**Comment by juliand665** [comment] 2022-02-27 03:42
I finally got around to trying this on Windows; still couldn't reproduce I'm afraid! Not sure what's going wrong for you…

**Comment by juliand665** [comment] 2022-03-28 19:00
closing this until further input.

**Closed by juliand665** 2022-03-28 19:00 UTC
Labels: bug, help wanted
