### ISSUE TITLE
Why doesn't dynamic FPS work with FastLoad?

### ISSUE THREAD

**Issue by StarsShine11904** [juliand665/Dynamic-FPS#169] opened 2024-02-22 13:34 UTC
Why can't it be executed with FastLoad after updating to 3.4.1? 
Can I know the reason?🤔

**Comment by LostLuma** [comment] 2024-02-22 15:37
Hello, quite a while it was reported to us that using Dynamic FPS and FastLoad together will lead to you being softlocked in the world loading screen (see #129). As mentioned in the aforementioned issue comments we luckily also have functionality to fix this behavior *if another mod requests it*, which I have reported on their [issue tracker](https://github.com/BumbleSoftware/Fastload/issues/108), and have also [submitted the fix for](https://github.com/BumbleSoftware/Fastload/pull/109).

Since the user experience of installing a bunch of mods and then simply being stuck on the world loading screen is arguable pretty poor I thought it would be acceptable to block all *current* versions of FastLoad from being loaded in tandem with Dynamic FPS, assuming that if they (at some point, it's been 150 days since it seems the author has quit modding ..?) make a new release the situation would be resolved.

The reason that I would've like FastLoad to adopt usage of this way of fixing the issue is that they can update their mod as they wish in the future and change it as needed, without us needing to keep track of their releases and shipping a new version of Dynamic FPS in case something significant changed.

---

With that being said, since the author seems to not intend to work on the mod again (and no one has stepped up to maintain it) it might be reasonable for us to fix this ourselves if FastLoad `3.4.0` or older is present (assuming if there's a future release it'll be fixed on their end).

For right now if you would like to run these mods together you can use a dependency override, they exist for both [Fabric](https://fabricmc.net/wiki/tutorial:dependency_overrides) and [Quilt](https://github.com/QuiltMC/quilt-loader/wiki/Dependency-Overrides).

**Comment by LostLuma** [comment] 2024-02-22 18:05
I've decided to actually spend some time doing this so this issue will be resolved in our next release.

**Closed** 2024-02-23 11:46 UTC
Labels: enhancement, support
