### ISSUE TITLE
Game closes without crash on lost focus

### ISSUE THREAD

**Issue by ProNoob135** [juliand665/Dynamic-FPS#65] opened 2022-07-15 20:52 UTC
I'm on quilt 0.17.1-beta.6, quilted fabric API 2.0.0-beta.6, 1.19

Around a third of the time I tab out, the game suddenly closes.
This is all that's sent to the log

`X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  38 (X_QueryPointer)
  Resource id in failed request:  0xd44615
  Serial number of failed request:  21209
  Current serial number in output stream:  21209
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1.`

**Comment by juliand665** [comment] 2022-07-17 17:16
Very strange! Is this on Windows? I'll have to try and reproduce there.

**Comment by ProNoob135** [comment] 2022-07-26 16:06
It's on Linux, using Xfce4

**Comment by ProNoob135** [comment] 2022-07-26 16:14
It wasn't an issue in 1.18. i'm curious what changed

**Comment by juliand665** [comment] 2022-07-27 03:08
As far as I know, pretty much nothing changed! The logic is all identical, all changes are just stuff that Mojang (or the mappings) moved around in 1.19…

Are you testing with just Dynamic FPS and no other mods? I don't really have a linux setup to reproduce this.

**Comment by ProNoob135** [comment] 2022-07-28 07:56
Yup, I tested without anything else. I'll try and get some better specifics if i can

**Comment by PgBiel** [comment] 2023-08-29 03:26
It's working fine in my Linux on 1.19.4 (using NixOS 23.05 as distro, KDE Plasma 5.27 as DE). Maybe the bug was fixed in the latest MC versions (or mod versions)?

**Comment by LostLuma** [comment] 2023-09-08 16:21
Might be interesting to see if it still happens in version 3.1.0 (build available only via [actions](https://github.com/juliand665/Dynamic-FPS/actions)).
I've refactored some internal things that directly interact with the window in #110 that might or might not help.

**Comment by LostLuma** [comment] 2023-12-16 11:41
I'm going to close this issue since we haven't gotten a response in multiple months, and it targets a very old version of the mod that is no longer supported. If you can still reproduce this on version 3.2.1 (or newer, once that's out) please comment with more information about your current platform etc. so we can maybe reproduce it (I was unable to).

**Closed by LostLuma** 2023-12-16 11:41 UTC
Labels: bug
